#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum StrategyTrait {
    AdDamage,
    AntiHeal,
    ApDamage,
    BacklineCarry,
    BasicAttacker,
    ChannelReliant,
    Cleanse,
    CritCarry,
    Debuffer,
    Disabler,
    Dive,
    Dot,
    Eeveelution,
    Execute,
    Frontline,
    HardCc,
    HealReliant,
    Healer,
    HighDefense,
    HighHealth,
    HighMobility,
    LowMobility,
    MeleeThreat,
    ObjectiveBurn,
    PercentHealthDamage,
    Poke,
    Shielding,
    SingleTargetAssassin,
    StanceSwitcher,
    Squishy,
    Sustain,
    TankBuster,
    TeamBuff,
    TypeFlexible,
    Untargetable,
    Zoner,
}

#[derive(Clone, Copy, Debug)]
pub struct PokemonStrategyInfo {
    pub id: &'static str,
    pub traits: &'static [StrategyTrait],
    pub threatens: &'static [StrategyTrait],
    pub vulnerable_to: &'static [StrategyTrait],
}

pub const POKEMON_STRATEGIES: [PokemonStrategyInfo; 101] = [
    PokemonStrategyInfo {
        id: "pokemon_moba_pikachu",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_charizard",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Dot,
            StrategyTrait::Zoner,
            StrategyTrait::Poke,
            StrategyTrait::Frontline,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_blastoise",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::Poke,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_feraligatr",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Sustain,
            StrategyTrait::Debuffer,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_emboar",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HardCc,
            StrategyTrait::Dive,
            StrategyTrait::TankBuster,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::HighHealth,
            StrategyTrait::LowMobility,
            StrategyTrait::BacklineCarry,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_blaziken",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::TeamBuff,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Healer,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_greninja",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::Untargetable,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_decidueye",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_inteleon",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::CritCarry,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Poke,
            StrategyTrait::Execute,
            StrategyTrait::Debuffer,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::HighHealth,
            StrategyTrait::LowMobility,
            StrategyTrait::BacklineCarry,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_skeledirge",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::HighHealth,
            StrategyTrait::Frontline,
            StrategyTrait::Dot,
            StrategyTrait::Disabler,
            StrategyTrait::Zoner,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::HealReliant,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::Poke,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_porygonz",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::TypeFlexible,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
            StrategyTrait::Disabler,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
            StrategyTrait::TypeFlexible,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_blissey",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::HighHealth,
            StrategyTrait::Sustain,
            StrategyTrait::Cleanse,
            StrategyTrait::TeamBuff,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Dot,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::Execute,
            StrategyTrait::Disabler,
            StrategyTrait::Dive,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_kleavor",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::Dot,
            StrategyTrait::CritCarry,
            StrategyTrait::Untargetable,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::Healer,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_scizor",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::CritCarry,
            StrategyTrait::Dive,
            StrategyTrait::Shielding,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_ursaluna",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::MeleeThreat,
            StrategyTrait::HardCc,
            StrategyTrait::Sustain,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::BasicAttacker,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Dive,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_sawk_throh",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::StanceSwitcher,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::HighHealth,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_hitmonchan",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
            StrategyTrait::MeleeThreat,
            StrategyTrait::HardCc,
            StrategyTrait::Dot,
            StrategyTrait::Sustain,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_hitmonlee",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::Dive,
            StrategyTrait::Disabler,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_hitmontop",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Debuffer,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::HighDefense,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::HighHealth,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_kilowattrel",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::HighMobility,
            StrategyTrait::Zoner,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Poke,
            StrategyTrait::BacklineCarry,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HighDefense,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_beeheeyem",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Disabler,
            StrategyTrait::Debuffer,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::HighDefense,
            StrategyTrait::HealReliant,
            StrategyTrait::Dot,
            StrategyTrait::Poke,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_gyarados",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Poke,
            StrategyTrait::Dot,
            StrategyTrait::Zoner,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_noivern",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Debuffer,
            StrategyTrait::HighMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::ChannelReliant,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_mantine",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::Zoner,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_cryogonal",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_vanilluxe",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_skarmory",
        traits: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
            StrategyTrait::HighHealth,
            StrategyTrait::Sustain,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::BasicAttacker,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Squishy,
            StrategyTrait::BacklineCarry,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::ApDamage,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_houndoom",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::Dot,
            StrategyTrait::Debuffer,
            StrategyTrait::HardCc,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
            StrategyTrait::Squishy,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_arbok",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Dot,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HighMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
            StrategyTrait::BacklineCarry,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Cleanse,
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_clawitzer",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_octillery",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_pyukumuku",
        traits: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::Dot,
            StrategyTrait::Debuffer,
            StrategyTrait::Sustain,
            StrategyTrait::TankBuster,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Dot,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::Cleanse,
            StrategyTrait::Execute,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_banette",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::Disabler,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::BasicAttacker,
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Poke,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_kricketune",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Zoner,
            StrategyTrait::TeamBuff,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::Dive,
            StrategyTrait::ChannelReliant,
            StrategyTrait::BasicAttacker,
        ],
        vulnerable_to: &[
            StrategyTrait::Cleanse,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_ambipom",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
            StrategyTrait::ObjectiveBurn,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_gallade",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Cleanse,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_audino",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::Shielding,
            StrategyTrait::TeamBuff,
            StrategyTrait::HighHealth,
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::Poke,
            StrategyTrait::Dot,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
            StrategyTrait::Execute,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_pangoro",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::Cleanse,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_passimian",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_oranguru",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::TeamBuff,
            StrategyTrait::Debuffer,
            StrategyTrait::Disabler,
            StrategyTrait::HighHealth,
            StrategyTrait::Frontline,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Squishy,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_dragalge",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Dot,
            StrategyTrait::Debuffer,
            StrategyTrait::Poke,
            StrategyTrait::Zoner,
            StrategyTrait::Sustain,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::HealReliant,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Cleanse,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_heliolisk",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Squishy,
            StrategyTrait::HardCc,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::Poke,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_turtonator",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::Zoner,
            StrategyTrait::Debuffer,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::HighMobility,
            StrategyTrait::Cleanse,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_ribombee",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Healer,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::BacklineCarry,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_smeargle",
        traits: &[
            StrategyTrait::TypeFlexible,
            StrategyTrait::Debuffer,
            StrategyTrait::Disabler,
            StrategyTrait::TeamBuff,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::ChannelReliant,
            StrategyTrait::BacklineCarry,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Dive,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_torterra",
        traits: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::Sustain,
            StrategyTrait::Shielding,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::BasicAttacker,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Poke,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::Execute,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_venusaur",
        traits: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HardCc,
            StrategyTrait::Sustain,
            StrategyTrait::Dot,
            StrategyTrait::Zoner,
            StrategyTrait::Debuffer,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_eevee",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::TeamBuff,
            StrategyTrait::Eeveelution,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Poke,
            StrategyTrait::Dot,
            StrategyTrait::Dive,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Disabler,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_jolteon",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::HighMobility,
            StrategyTrait::Poke,
            StrategyTrait::Eeveelution,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_flareon",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Dot,
            StrategyTrait::Poke,
            StrategyTrait::Zoner,
            StrategyTrait::Eeveelution,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::HealReliant,
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_vaporeon",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::Healer,
            StrategyTrait::Sustain,
            StrategyTrait::Debuffer,
            StrategyTrait::Eeveelution,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::Poke,
            StrategyTrait::Frontline,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::Disabler,
            StrategyTrait::Execute,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_leafeon",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dot,
            StrategyTrait::Dive,
            StrategyTrait::Eeveelution,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Healer,
            StrategyTrait::Squishy,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::Poke,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_glaceon",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::HardCc,
            StrategyTrait::Zoner,
            StrategyTrait::Eeveelution,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::Dive,
            StrategyTrait::LowMobility,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_umbreon",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Disabler,
            StrategyTrait::Untargetable,
            StrategyTrait::Eeveelution,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Healer,
            StrategyTrait::Squishy,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::Frontline,
            StrategyTrait::TankBuster,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_espeon",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Debuffer,
            StrategyTrait::Disabler,
            StrategyTrait::Poke,
            StrategyTrait::Eeveelution,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_sylveon",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::Cleanse,
            StrategyTrait::Zoner,
            StrategyTrait::TeamBuff,
            StrategyTrait::Eeveelution,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::Dot,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Eeveelution,
        ],
        vulnerable_to: &[
            StrategyTrait::Disabler,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Poke,
            StrategyTrait::Eeveelution,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_comfey",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::TeamBuff,
            StrategyTrait::Untargetable,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::Poke,
            StrategyTrait::Dot,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::Execute,
            StrategyTrait::HardCc,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_drampa",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::HardCc,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::Execute,
            StrategyTrait::AntiHeal,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_kommoo",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
        ],
        threatens: &[
            StrategyTrait::HighHealth,
            StrategyTrait::Frontline,
            StrategyTrait::HealReliant,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::BacklineCarry,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_thievul",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::AntiHeal,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::Sustain,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Frontline,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_archaludon",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
            StrategyTrait::Poke,
            StrategyTrait::Debuffer,
            StrategyTrait::AntiHeal,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_appletun",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::ApDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::Debuffer,
            StrategyTrait::Sustain,
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::HighDefense,
            StrategyTrait::Frontline,
            StrategyTrait::Sustain,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
            StrategyTrait::Poke,
            StrategyTrait::BacklineCarry,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_goodra",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::Healer,
            StrategyTrait::Sustain,
            StrategyTrait::TeamBuff,
            StrategyTrait::Disabler,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::HealReliant,
            StrategyTrait::TeamBuff,
            StrategyTrait::LowMobility,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
            StrategyTrait::BacklineCarry,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_dedenne",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Dive,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Zoner,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::LowMobility,
            StrategyTrait::ChannelReliant,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Frontline,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_hawlucha",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Dive,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Frontline,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_bouffalant",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::HardCc,
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::LowMobility,
            StrategyTrait::BacklineCarry,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
            StrategyTrait::Poke,
            StrategyTrait::AntiHeal,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_starmie",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::ChannelReliant,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
            StrategyTrait::Dive,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_drednaw",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::LowMobility,
            StrategyTrait::HardCc,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::TankBuster,
            StrategyTrait::PercentHealthDamage,
            StrategyTrait::Poke,
            StrategyTrait::AntiHeal,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_orbeetle",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Disabler,
            StrategyTrait::Dot,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Frontline,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_coalossal",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::LowMobility,
            StrategyTrait::Zoner,
        ],
        threatens: &[
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::TankBuster,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_magmortar",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::CritCarry,
            StrategyTrait::Poke,
            StrategyTrait::Dot,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_grapploct",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::MeleeThreat,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::HardCc,
            StrategyTrait::BasicAttacker,
            StrategyTrait::Sustain,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::ChannelReliant,
            StrategyTrait::HardCc,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::BacklineCarry,
            StrategyTrait::AntiHeal,
            StrategyTrait::Disabler,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_sirfetchd",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::MeleeThreat,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HighHealth,
            StrategyTrait::ObjectiveBurn,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Disabler,
            StrategyTrait::HighDefense,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_arboliva",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Zoner,
            StrategyTrait::Dot,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_armarouge",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::MeleeThreat,
            StrategyTrait::HardCc,
            StrategyTrait::Dot,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BacklineCarry,
            StrategyTrait::LowMobility,
            StrategyTrait::BasicAttacker,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::Disabler,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_ceruledge",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Execute,
            StrategyTrait::HardCc,
            StrategyTrait::Dot,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Frontline,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_gholdengo",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Debuffer,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_frosmoth",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::ApDamage,
            StrategyTrait::ChannelReliant,
            StrategyTrait::Squishy,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::BacklineCarry,
            StrategyTrait::HighDefense,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_shedinja",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::Untargetable,
            StrategyTrait::Squishy,
            StrategyTrait::HighMobility,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_ludicolo",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::Sustain,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Debuffer,
            StrategyTrait::TeamBuff,
            StrategyTrait::Frontline,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::ChannelReliant,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::Cleanse,
            StrategyTrait::Poke,
            StrategyTrait::BacklineCarry,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_kingdra",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::ApDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_delibird",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Healer,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::HealReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_cloyster",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BacklineCarry,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Frontline,
            StrategyTrait::Sustain,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::CritCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Dive,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::HighDefense,
            StrategyTrait::HardCc,
            StrategyTrait::AntiHeal,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_electrode",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::Cleanse,
            StrategyTrait::Dive,
            StrategyTrait::Execute,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::ChannelReliant,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::TankBuster,
            StrategyTrait::Untargetable,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_snorlax",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::Frontline,
            StrategyTrait::HighDefense,
            StrategyTrait::HighHealth,
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Sustain,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_zeraora",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Disabler,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Poke,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_rillaboom",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::TeamBuff,
            StrategyTrait::Sustain,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Zoner,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Dive,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::Poke,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::TankBuster,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_dragapult",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::ApDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Sustain,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::BacklineCarry,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::HardCc,
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_shiftry",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HighMobility,
            StrategyTrait::HardCc,
            StrategyTrait::Disabler,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
            StrategyTrait::LowMobility,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_sigilyph",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::Zoner,
            StrategyTrait::Debuffer,
            StrategyTrait::Disabler,
            StrategyTrait::BacklineCarry,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::Frontline,
            StrategyTrait::ChannelReliant,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_weavile",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::Dive,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::BacklineCarry,
            StrategyTrait::ChannelReliant,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::HighDefense,
            StrategyTrait::Disabler,
            StrategyTrait::Frontline,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_swanna",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::HighMobility,
            StrategyTrait::Zoner,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::TeamBuff,
            StrategyTrait::Frontline,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HardCc,
            StrategyTrait::AntiHeal,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_marowak",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::CritCarry,
            StrategyTrait::BacklineCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
            StrategyTrait::PercentHealthDamage,
        ],
        threatens: &[
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::LowMobility,
            StrategyTrait::ObjectiveBurn,
        ],
        vulnerable_to: &[
            StrategyTrait::Dive,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::HighMobility,
            StrategyTrait::HardCc,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_garganacl",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::Frontline,
            StrategyTrait::HighHealth,
            StrategyTrait::HighDefense,
            StrategyTrait::LowMobility,
            StrategyTrait::Zoner,
            StrategyTrait::Debuffer,
            StrategyTrait::AntiHeal,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::Healer,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
            StrategyTrait::HighMobility,
            StrategyTrait::PercentHealthDamage,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_ampharos",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Zoner,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Debuffer,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::Untargetable,
            StrategyTrait::HighMobility,
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::Poke,
            StrategyTrait::HardCc,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_xatu",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Poke,
            StrategyTrait::Debuffer,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::ChannelReliant,
            StrategyTrait::LowMobility,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::LowMobility,
            StrategyTrait::ChannelReliant,
            StrategyTrait::Squishy,
            StrategyTrait::Poke,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HighMobility,
            StrategyTrait::HardCc,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_quaquaval",
        traits: &[
            StrategyTrait::AdDamage,
            StrategyTrait::BasicAttacker,
            StrategyTrait::BacklineCarry,
            StrategyTrait::ObjectiveBurn,
            StrategyTrait::HighMobility,
            StrategyTrait::Poke,
            StrategyTrait::Disabler,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::TankBuster,
            StrategyTrait::Dive,
        ],
        vulnerable_to: &[
            StrategyTrait::HardCc,
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Poke,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_arcanine",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Sustain,
            StrategyTrait::HighHealth,
            StrategyTrait::Debuffer,
            StrategyTrait::Dot,
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
        ],
        threatens: &[
            StrategyTrait::MeleeThreat,
            StrategyTrait::BasicAttacker,
            StrategyTrait::Dive,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::Poke,
            StrategyTrait::AntiHeal,
            StrategyTrait::TankBuster,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_missingno",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Debuffer,
            StrategyTrait::Disabler,
            StrategyTrait::Dot,
            StrategyTrait::Zoner,
            StrategyTrait::Poke,
            StrategyTrait::TeamBuff,
            StrategyTrait::Squishy,
        ],
        threatens: &[
            StrategyTrait::TeamBuff,
            StrategyTrait::HealReliant,
            StrategyTrait::BacklineCarry,
            StrategyTrait::ChannelReliant,
            StrategyTrait::LowMobility,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_yanmega",
        traits: &[
            StrategyTrait::ApDamage,
            StrategyTrait::Dot,
            StrategyTrait::AntiHeal,
            StrategyTrait::Debuffer,
            StrategyTrait::Poke,
            StrategyTrait::Sustain,
            StrategyTrait::Zoner,
            StrategyTrait::HighHealth,
        ],
        threatens: &[
            StrategyTrait::HealReliant,
            StrategyTrait::Sustain,
            StrategyTrait::Frontline,
            StrategyTrait::LowMobility,
            StrategyTrait::MeleeThreat,
        ],
        vulnerable_to: &[
            StrategyTrait::SingleTargetAssassin,
            StrategyTrait::Dive,
            StrategyTrait::HardCc,
            StrategyTrait::HighMobility,
            StrategyTrait::BacklineCarry,
        ],
    },
    PokemonStrategyInfo {
        id: "pokemon_moba_wishiwashi",
        traits: &[
            StrategyTrait::Healer,
            StrategyTrait::HealReliant,
            StrategyTrait::Shielding,
            StrategyTrait::TeamBuff,
            StrategyTrait::Disabler,
            StrategyTrait::HardCc,
            StrategyTrait::Frontline,
        ],
        threatens: &[
            StrategyTrait::Dive,
            StrategyTrait::MeleeThreat,
            StrategyTrait::LowMobility,
            StrategyTrait::SingleTargetAssassin,
        ],
        vulnerable_to: &[
            StrategyTrait::AntiHeal,
            StrategyTrait::HardCc,
            StrategyTrait::Poke,
            StrategyTrait::TankBuster,
        ],
    },
];

pub fn strategy_for_champion_id(champion_id: &str) -> Option<&'static PokemonStrategyInfo> {
    POKEMON_STRATEGIES
        .iter()
        .find(|strategy| strategy.id == champion_id)
}

pub fn has_trait(strategy: &PokemonStrategyInfo, strategy_trait: StrategyTrait) -> bool {
    strategy
        .traits
        .iter()
        .any(|candidate| *candidate == strategy_trait)
}

pub fn shared_trait_count(left: &[StrategyTrait], right: &[StrategyTrait]) -> usize {
    left.iter()
        .filter(|candidate| right.iter().any(|other| other == *candidate))
        .count()
}
